const REGISTER = "REGISTER";
const SIGN_IN = "SIGN_IN" ; 
const LOGGED_OUT = "LOGGED_OUT" ;
const LOGGED_IN = "LOGGED_IN" ;
const LIST_COUNTRY = "LIST_COUNTRY";
const LIST_GRADE= "LIST_GRADE" ;
const LIST_TERMS = "LIST_TERMS" ; 
const LIST_SUBJECTS = "LIST_SUBJECTS" ; 
const LIST_CHAPTERS = "LIST_CHAPTERS" ; 
const LIST_LESSONS = "LIST_LESSONS" ; 
const LIST_SECTIONS = "LIST_SECTIONS" ; 
const LIST_COURSE_ENROLL_REQUEST = "LIST_COURSE_ENROLL_REQUEST"
const LIST_GENDER = "LIST_GENDER";
const LIST_ROLE = "LIST_ROLE";
const LIST_TEACHER_COURSES = "LIST_TEACHER_COURSES"
const LIST_STUDENT_COURSES = "LIST_STUDENT_COURSES"
const LIST_MESSAGES = "LIST_MESSAGES";
const GET_COURSE = "GET_COURSE";





// const APIURL = "http://git.arabook.net" ;
const GET_CURRENT_USER ="GET_CURRENT_USER" ;
const APIURL = "http://127.0.0.1:6500" ;


module.exports = {
    APIURL,
    SIGN_IN,
    LOGGED_OUT,
    LOGGED_IN,
    REGISTER,
    LIST_COUNTRY,
    LIST_GRADE,
    LIST_TERMS,
    LIST_SUBJECTS,
    LIST_CHAPTERS,
    LIST_LESSONS,
    LIST_SECTIONS,
    LIST_COURSE_ENROLL_REQUEST,
    LIST_GENDER,
    LIST_ROLE,
    GET_CURRENT_USER,
    LIST_TEACHER_COURSES,
    LIST_STUDENT_COURSES,
    LIST_MESSAGES,
    GET_COURSE,
 } ; 